### ISSUE TITLE
P3-Project Planning feedback

### ISSUE THREAD

**Issue by dcmorse** [Judy2001/liftoff-assignments#3]
Nice work. Your stories are clear. Your wireframes are clear. The [pie charts](https://github.com/Judy2001/liftoff-assignments/blob/master/P3-Project_Planning/piecharts-with-edit-or-logout-page.jpg) are exciting, I like the work you put into the little explanatory notes. 

Couple-a suggestions:
- You probably will prefer to have created the project board on the 401k project, not on the liftoff assignments project. That way, all the stuff for the project is in one place, prospective employers are more likely to find it, etc. I bet the fastest way to change that is to just copy the cards 1-by-1. 
- Your stories in your 'To do' column seem to be in reverse order. Typically the next thing to be done goes on top. 

Please fix these issues when you have the time. Close this issue when you want.

**Comment by Judy2001** [comment]
Thanks for the feedback; both issues are fixed.
