### ISSUE TITLE
C1 - Online Profiles linkedin feedback

### ISSUE THREAD

**Issue by dcmorse** [Judy2001/liftoff-assignments#5]
For your LinkedIn profile please add at a minimum some of your core technical skills. Looking at the profile from the outside it's not obvious you are seeking employment as a programmer. 

Change your occupation from "Student at LaunchCode" to "Programmer" or "Software Developer" or "Software Engineer" - whichever term you like best. 

LinkedIn gives most people a lot of feelings, but it is a useful collaborating tool for mutual connections, and I think it's necessary to put in the work and work up a decent profile. 

For the optional stuff, I'm just going to quote the entire LinkedIn Grading Rubric at you:

## Nice to Haves

If a student has included these, feel free to give positive feedback and any critique, but ultimately it's just...nice to have.

- Summary - A brief description about themselves, their journey, or what they enjoy. 
- Work history details - Ideally highlighting relevant/transferable skills.
- Volunteer Experience
- Skills and Endorsements - Ideally applicable skills, but use your best judgement.

## Potential Feedback

- Add a professional looking picture. Having a picture helps the interviewer see you as more than just a name, or a resume. It also helps the interviewer recognize you when you come in for an interview, and will help them remember you after the interview! Also a picture is a sign of an active profile.
- Add a summary. We highly recommend adding a summary. In your summary you can explain you are looking for a job, and summarize your learning journey so far. Or you can state that you are planning on transitioning careers and you can summarize your career so far, and the new technical skills you have been focusing on. Or you can even state you are learning new skills as professional development for your current career.
- Make connections with professionals you know! LinkedIn is not like Twitter where you follow every person you can think of, or like Facebook where you add people you knew from 10 years ago. LinkedIn is the professional social media site. You should only make connections with people you know professionally. If you can't think of any professionals you know in the tech industry start by adding some members of this class, or a Mentor, or an Instructor, and continue adding connections when you meet other tech professionals.
- Use LinkedIn to follow up with interviewers. After you interview with a company you can add the interviewers as connections. Even if they decide not to hire you, you can still connect with them.

**Comment by Judy2001** [comment]
I was finished with everything but the picture on LinkedIn on Thursday.  That darn picture was a major issue!
